### ISSUE TITLE
Pssttt

### ISSUE THREAD

**Issue by riemers** [mgrefsrud/home-assistant-config#1]
https://github.com/mgrefsrud/home-assistant-config/tree/67650f021a9e098bb403891b3d59a4a44ca0840f/themes/.storage

i don't think that should be there.. don't store the .storage folder online. Just a headsup ;)

**Comment by mgrefsrud** [comment]
Thanks for the headsup, i do not know how it got in that folder.

**Comment by riemers** [comment]
It looked like a rather "mistake" hence why i reported it. After this i was searching github for .storage folders, you would be amazed..
